[2025-01-23T13:53:07.697+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-23T13:53:07.707+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cr_table_snowflake.retrieve_data_query manual__2025-01-23T13:52:56.388665+00:00 [queued]>
[2025-01-23T13:53:07.712+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cr_table_snowflake.retrieve_data_query manual__2025-01-23T13:52:56.388665+00:00 [queued]>
[2025-01-23T13:53:07.712+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-23T13:53:07.721+0000] {taskinstance.py:2889} INFO - Executing <Task(SnowflakeOperator): retrieve_data_query> on 2025-01-23 13:52:56.388665+00:00
[2025-01-23T13:53:07.728+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=9553) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-23T13:53:07.730+0000] {standard_task_runner.py:72} INFO - Started process 9554 to run task
[2025-01-23T13:53:07.732+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cr_table_snowflake', 'retrieve_data_query', 'manual__2025-01-23T13:52:56.388665+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/create_table.py', '--cfg-path', '/tmp/tmphfslnpba']
[2025-01-23T13:53:07.734+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask retrieve_data_query
[2025-01-23T13:53:07.767+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cr_table_snowflake.retrieve_data_query manual__2025-01-23T13:52:56.388665+00:00 [running]> on host c28716311b4b
[2025-01-23T13:53:07.818+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cr_table_snowflake' AIRFLOW_CTX_TASK_ID='retrieve_data_query' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T13:52:56.388665+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-23T13:52:56.388665+00:00'
[2025-01-23T13:53:07.819+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-23T13:53:07.820+0000] {sql.py:278} INFO - Executing: SELECT * FROM employees;
[2025-01-23T13:53:07.828+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-01-23T13:53:07.836+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-01-23T13:53:07.837+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-6.12.10-orbstack-00297-gf8f6e015b993-aarch64-with-glibc2.36
[2025-01-23T13:53:07.837+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2025-01-23T13:53:07.838+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-01-23T13:53:08.140+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-01-23T13:53:08.140+0000] {sql.py:553} INFO - Running statement: SELECT * FROM employees;, parameters: None
[2025-01-23T13:53:08.363+0000] {cursor.py:1166} INFO - Number of results in first chunk: 5
[2025-01-23T13:53:08.363+0000] {sql.py:562} INFO - Rows affected: 5
[2025-01-23T13:53:08.364+0000] {snowflake.py:447} INFO - Rows affected: 5
[2025-01-23T13:53:08.365+0000] {snowflake.py:448} INFO - Snowflake query id: 01b9e7a1-3201-6405-000b-894e000209f6
[2025-01-23T13:53:08.416+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-01-23T13:53:08.417+0000] {connection.py:789} INFO - closed
[2025-01-23T13:53:08.453+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2025-01-23T13:53:08.597+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-23T13:53:08.598+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cr_table_snowflake, task_id=retrieve_data_query, run_id=manual__2025-01-23T13:52:56.388665+00:00, execution_date=20250123T135256, start_date=20250123T135307, end_date=20250123T135308
[2025-01-23T13:53:08.646+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-23T13:53:08.666+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-23T13:53:08.671+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
