[2025-01-23T04:17:43.431+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-23T04:17:43.443+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_process.dbt_run scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-23T04:17:43.448+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_process.dbt_run scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-23T04:17:43.448+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-23T04:17:43.463+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): dbt_run> on 2025-01-22 00:00:00+00:00
[2025-01-23T04:17:43.467+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3933) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-23T04:17:43.468+0000] {standard_task_runner.py:72} INFO - Started process 3934 to run task
[2025-01-23T04:17:43.469+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_process', 'dbt_run', 'scheduled__2025-01-22T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/test_dbt_process.py', '--cfg-path', '/tmp/tmpdzo2wax4']
[2025-01-23T04:17:43.470+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask dbt_run
[2025-01-23T04:17:43.508+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_process.dbt_run scheduled__2025-01-22T00:00:00+00:00 [running]> on host c28716311b4b
[2025-01-23T04:17:43.556+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_process' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T00:00:00+00:00'
[2025-01-23T04:17:43.557+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-23T04:17:43.559+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-23T04:17:43.559+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/include/dbt/northwind/ && dbt run']
[2025-01-23T04:17:43.564+0000] {subprocess.py:99} INFO - Output:
[2025-01-23T04:17:45.186+0000] {subprocess.py:106} INFO - [0m04:17:45  Running with dbt=1.8.7
[2025-01-23T04:17:45.924+0000] {subprocess.py:106} INFO - [0m04:17:45  Registered adapter: snowflake=1.8.4
[2025-01-23T04:17:46.090+0000] {subprocess.py:106} INFO - [0m04:17:46  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-01-23T04:17:46.091+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-01-23T04:17:46.091+0000] {subprocess.py:106} INFO - - models.northwind.example
[2025-01-23T04:17:46.184+0000] {subprocess.py:106} INFO - [0m04:17:46  Found 2 seeds, 1 model, 1 source, 459 macros
[2025-01-23T04:17:46.185+0000] {subprocess.py:106} INFO - [0m04:17:46
[2025-01-23T04:17:47.093+0000] {subprocess.py:106} INFO - [0m04:17:47  Concurrency: 200 threads (target='dev')
[2025-01-23T04:17:47.095+0000] {subprocess.py:106} INFO - [0m04:17:47
[2025-01-23T04:17:47.171+0000] {subprocess.py:106} INFO - [0m04:17:47  1 of 1 START sql view model public.dim_customer ................................ [RUN]
[2025-01-23T04:17:47.889+0000] {subprocess.py:106} INFO - [0m04:17:47  1 of 1 OK created sql view model public.dim_customer ........................... [[32mSUCCESS 1[0m in 0.71s]
[2025-01-23T04:17:47.911+0000] {subprocess.py:106} INFO - [0m04:17:47
[2025-01-23T04:17:47.914+0000] {subprocess.py:106} INFO - [0m04:17:47  Finished running 1 view model in 0 hours 0 minutes and 1.73 seconds (1.73s).
[2025-01-23T04:17:47.935+0000] {subprocess.py:106} INFO - [0m04:17:47
[2025-01-23T04:17:47.936+0000] {subprocess.py:106} INFO - [0m04:17:47  [32mCompleted successfully[0m
[2025-01-23T04:17:47.936+0000] {subprocess.py:106} INFO - [0m04:17:47
[2025-01-23T04:17:47.937+0000] {subprocess.py:106} INFO - [0m04:17:47  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-01-23T04:17:49.431+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-23T04:17:49.462+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-23T04:17:49.462+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_process, task_id=dbt_run, run_id=scheduled__2025-01-22T00:00:00+00:00, execution_date=20250122T000000, start_date=20250123T041743, end_date=20250123T041749
[2025-01-23T04:17:49.510+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-23T04:17:49.522+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-23T04:17:49.525+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
